version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    labels:
      - "dependencies"
    versioning-strategy: increase
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
      rollup:
        patterns:
          - "@rollup/*"
          - "@types/rollup-*"
          - "rollup"
          - "rollup-plugin-*"
      testing:
        patterns:
          - "@testing-library/*"
          - "@storybook/testing-library"
          - "@types/jest"
          - "jest"
          - "jest-*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
