export const AUTO_DISMISS_TIMEOUT_MS = 5000;
export const AUTO_DISMISS_WARNING_MIN_TIMEOUT_MS = 5000;
export const AUTO_DISMISS_WARNING_MAX_TIMEOUT_MS = 10000;
export const AUTO_DISMISS_ERROR_TIMEOUT_MS = 30000;
