name: Build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci
      env:
        FORT_AWESOME_TOKEN: ${{ secrets.FORT_AWESOME_TOKEN }}

    - name: Run linter
      run: npm run lint

    - name: Run typecheck
      run: npm run typecheck

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test:ci
